version: '3.5'
services:
  go_react:
    container_name: go_react
    hostname: go_react
    image: go_react
    ports:
      - '5173:5173'
    command: sleep infinity
    # command: npm run dev -- --host 0.0.0.0  # Assuming you're using Vite's dev server
    build:
      context: .
      dockerfile: go_react.Dockerfile
    volumes:
      - ./:/opt/go_react
    environment:
      - HOST=0.0.0.0 # This ensures the dev server binds to all network interfaces

  scrapers:
    container_name: scrapers
    hostname: scrapers
    image: scrapers
    ports:
      - '5174:5174'
    command: sleep infinity
    build:
      context: .
      dockerfile: scrapers.Dockerfile
    volumes:
      - ./:/opt/scrapers
    environment:
      - HOST=0.0.0.0 # This ensures the dev server binds to all network interfaces
      - PORT=5174

  json_server:
    container_name: json_server
    hostname: json_server
    image: json_server
    build:
      context: .
      dockerfile: json_server.Dockerfile
    volumes:
      - ./:/opt/json_server
    ports:
      - '8080:8080'
    environment:
      - HOST=0.0.0.0 # This ensures the dev server binds to all network interfaces
    command: go run main.go